
package br.edu.ifnmg.client.service;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "RpgDiceService", targetNamespace = "http://service.rpgdice.ifnmg.edu.br/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface RpgDiceService {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.rpgdice.ifnmg.edu.br/RpgDiceService/roll20Request", output = "http://service.rpgdice.ifnmg.edu.br/RpgDiceService/roll20Response")
    public int roll20(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
