
package br.edu.ifnmg.client.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "RpgDiceServiceImplService", targetNamespace = "http://service.rpgdice.ifnmg.edu.br/", wsdlLocation = "http://localhost:8080/service/rpgdice?wsdl")
public class RpgDiceServiceImplService
    extends Service
{

    private final static URL RPGDICESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RPGDICESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName RPGDICESERVICEIMPLSERVICE_QNAME = new QName("http://service.rpgdice.ifnmg.edu.br/", "RpgDiceServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/service/rpgdice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RPGDICESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        RPGDICESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public RpgDiceServiceImplService() {
        super(__getWsdlLocation(), RPGDICESERVICEIMPLSERVICE_QNAME);
    }

    public RpgDiceServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RPGDICESERVICEIMPLSERVICE_QNAME, features);
    }

    public RpgDiceServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, RPGDICESERVICEIMPLSERVICE_QNAME);
    }

    public RpgDiceServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RPGDICESERVICEIMPLSERVICE_QNAME, features);
    }

    public RpgDiceServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RpgDiceServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RpgDiceService
     */
    @WebEndpoint(name = "RpgDiceServiceImplPort")
    public RpgDiceService getRpgDiceServiceImplPort() {
        return super.getPort(new QName("http://service.rpgdice.ifnmg.edu.br/", "RpgDiceServiceImplPort"), RpgDiceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RpgDiceService
     */
    @WebEndpoint(name = "RpgDiceServiceImplPort")
    public RpgDiceService getRpgDiceServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.rpgdice.ifnmg.edu.br/", "RpgDiceServiceImplPort"), RpgDiceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RPGDICESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw RPGDICESERVICEIMPLSERVICE_EXCEPTION;
        }
        return RPGDICESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
